// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	App               *app
	AppLocalization   *appLocalization
	AppProviderConfig *appProviderConfig
	AppUser           *appUser
	Project           *project
	ProviderConfig    *providerConfig
	Subscription      *subscription
	Translation       *translation
	TranslationQueue  *translationQueue
	User              *user
	UserActivity      *userActivity
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	App = &Q.App
	AppLocalization = &Q.AppLocalization
	AppProviderConfig = &Q.AppProviderConfig
	AppUser = &Q.AppUser
	Project = &Q.Project
	ProviderConfig = &Q.ProviderConfig
	Subscription = &Q.Subscription
	Translation = &Q.Translation
	TranslationQueue = &Q.TranslationQueue
	User = &Q.User
	UserActivity = &Q.UserActivity
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		App:               newApp(db, opts...),
		AppLocalization:   newAppLocalization(db, opts...),
		AppProviderConfig: newAppProviderConfig(db, opts...),
		AppUser:           newAppUser(db, opts...),
		Project:           newProject(db, opts...),
		ProviderConfig:    newProviderConfig(db, opts...),
		Subscription:      newSubscription(db, opts...),
		Translation:       newTranslation(db, opts...),
		TranslationQueue:  newTranslationQueue(db, opts...),
		User:              newUser(db, opts...),
		UserActivity:      newUserActivity(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	App               app
	AppLocalization   appLocalization
	AppProviderConfig appProviderConfig
	AppUser           appUser
	Project           project
	ProviderConfig    providerConfig
	Subscription      subscription
	Translation       translation
	TranslationQueue  translationQueue
	User              user
	UserActivity      userActivity
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		App:               q.App.clone(db),
		AppLocalization:   q.AppLocalization.clone(db),
		AppProviderConfig: q.AppProviderConfig.clone(db),
		AppUser:           q.AppUser.clone(db),
		Project:           q.Project.clone(db),
		ProviderConfig:    q.ProviderConfig.clone(db),
		Subscription:      q.Subscription.clone(db),
		Translation:       q.Translation.clone(db),
		TranslationQueue:  q.TranslationQueue.clone(db),
		User:              q.User.clone(db),
		UserActivity:      q.UserActivity.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		App:               q.App.replaceDB(db),
		AppLocalization:   q.AppLocalization.replaceDB(db),
		AppProviderConfig: q.AppProviderConfig.replaceDB(db),
		AppUser:           q.AppUser.replaceDB(db),
		Project:           q.Project.replaceDB(db),
		ProviderConfig:    q.ProviderConfig.replaceDB(db),
		Subscription:      q.Subscription.replaceDB(db),
		Translation:       q.Translation.replaceDB(db),
		TranslationQueue:  q.TranslationQueue.replaceDB(db),
		User:              q.User.replaceDB(db),
		UserActivity:      q.UserActivity.replaceDB(db),
	}
}

type queryCtx struct {
	App               IAppDo
	AppLocalization   IAppLocalizationDo
	AppProviderConfig IAppProviderConfigDo
	AppUser           IAppUserDo
	Project           IProjectDo
	ProviderConfig    IProviderConfigDo
	Subscription      ISubscriptionDo
	Translation       ITranslationDo
	TranslationQueue  ITranslationQueueDo
	User              IUserDo
	UserActivity      IUserActivityDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		App:               q.App.WithContext(ctx),
		AppLocalization:   q.AppLocalization.WithContext(ctx),
		AppProviderConfig: q.AppProviderConfig.WithContext(ctx),
		AppUser:           q.AppUser.WithContext(ctx),
		Project:           q.Project.WithContext(ctx),
		ProviderConfig:    q.ProviderConfig.WithContext(ctx),
		Subscription:      q.Subscription.WithContext(ctx),
		Translation:       q.Translation.WithContext(ctx),
		TranslationQueue:  q.TranslationQueue.WithContext(ctx),
		User:              q.User.WithContext(ctx),
		UserActivity:      q.UserActivity.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
