// Package dao provides data access objects generated by GORM gen
package dao

import (
	"gorm.io/gorm"
)

// Initialize provides database initialization for the DAO layer
func Initialize(db *gorm.DB) {
	// This function can be used to initialize generated queries
	// with the database connection if needed
}
