// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/fdddf/xcstrings-translator/internal/database"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAppUser(db *gorm.DB, opts ...gen.DOOption) appUser {
	_appUser := appUser{}

	_appUser.appUserDo.UseDB(db, opts...)
	_appUser.appUserDo.UseModel(&database.AppUser{})

	tableName := _appUser.appUserDo.TableName()
	_appUser.ALL = field.NewAsterisk(tableName)
	_appUser.ID = field.NewUint(tableName, "id")
	_appUser.CreatedAt = field.NewTime(tableName, "created_at")
	_appUser.UpdatedAt = field.NewTime(tableName, "updated_at")
	_appUser.DeletedAt = field.NewField(tableName, "deleted_at")
	_appUser.AppID = field.NewUint(tableName, "app_id")
	_appUser.UserID = field.NewUint(tableName, "user_id")
	_appUser.Role = field.NewString(tableName, "role")
	_appUser.App = appUserBelongsToApp{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("App", "database.App"),
		User: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("App.User", "database.User"),
		},
	}

	_appUser.User = appUserBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "database.User"),
	}

	_appUser.fillFieldMap()

	return _appUser
}

type appUser struct {
	appUserDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	AppID     field.Uint
	UserID    field.Uint
	Role      field.String
	App       appUserBelongsToApp

	User appUserBelongsToUser

	fieldMap map[string]field.Expr
}

func (a appUser) Table(newTableName string) *appUser {
	a.appUserDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appUser) As(alias string) *appUser {
	a.appUserDo.DO = *(a.appUserDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appUser) updateTableName(table string) *appUser {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.AppID = field.NewUint(table, "app_id")
	a.UserID = field.NewUint(table, "user_id")
	a.Role = field.NewString(table, "role")

	a.fillFieldMap()

	return a
}

func (a *appUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appUser) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 9)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["role"] = a.Role

}

func (a appUser) clone(db *gorm.DB) appUser {
	a.appUserDo.ReplaceConnPool(db.Statement.ConnPool)
	a.App.db = db.Session(&gorm.Session{Initialized: true})
	a.App.db.Statement.ConnPool = db.Statement.ConnPool
	a.User.db = db.Session(&gorm.Session{Initialized: true})
	a.User.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a appUser) replaceDB(db *gorm.DB) appUser {
	a.appUserDo.ReplaceDB(db)
	a.App.db = db.Session(&gorm.Session{})
	a.User.db = db.Session(&gorm.Session{})
	return a
}

type appUserBelongsToApp struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
	}
}

func (a appUserBelongsToApp) Where(conds ...field.Expr) *appUserBelongsToApp {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a appUserBelongsToApp) WithContext(ctx context.Context) *appUserBelongsToApp {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a appUserBelongsToApp) Session(session *gorm.Session) *appUserBelongsToApp {
	a.db = a.db.Session(session)
	return &a
}

func (a appUserBelongsToApp) Model(m *database.AppUser) *appUserBelongsToAppTx {
	return &appUserBelongsToAppTx{a.db.Model(m).Association(a.Name())}
}

func (a appUserBelongsToApp) Unscoped() *appUserBelongsToApp {
	a.db = a.db.Unscoped()
	return &a
}

type appUserBelongsToAppTx struct{ tx *gorm.Association }

func (a appUserBelongsToAppTx) Find() (result *database.App, err error) {
	return result, a.tx.Find(&result)
}

func (a appUserBelongsToAppTx) Append(values ...*database.App) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a appUserBelongsToAppTx) Replace(values ...*database.App) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a appUserBelongsToAppTx) Delete(values ...*database.App) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a appUserBelongsToAppTx) Clear() error {
	return a.tx.Clear()
}

func (a appUserBelongsToAppTx) Count() int64 {
	return a.tx.Count()
}

func (a appUserBelongsToAppTx) Unscoped() *appUserBelongsToAppTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type appUserBelongsToUser struct {
	db *gorm.DB

	field.RelationField
}

func (a appUserBelongsToUser) Where(conds ...field.Expr) *appUserBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a appUserBelongsToUser) WithContext(ctx context.Context) *appUserBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a appUserBelongsToUser) Session(session *gorm.Session) *appUserBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a appUserBelongsToUser) Model(m *database.AppUser) *appUserBelongsToUserTx {
	return &appUserBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a appUserBelongsToUser) Unscoped() *appUserBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type appUserBelongsToUserTx struct{ tx *gorm.Association }

func (a appUserBelongsToUserTx) Find() (result *database.User, err error) {
	return result, a.tx.Find(&result)
}

func (a appUserBelongsToUserTx) Append(values ...*database.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a appUserBelongsToUserTx) Replace(values ...*database.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a appUserBelongsToUserTx) Delete(values ...*database.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a appUserBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a appUserBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a appUserBelongsToUserTx) Unscoped() *appUserBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type appUserDo struct{ gen.DO }

type IAppUserDo interface {
	gen.SubQuery
	Debug() IAppUserDo
	WithContext(ctx context.Context) IAppUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppUserDo
	WriteDB() IAppUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppUserDo
	Not(conds ...gen.Condition) IAppUserDo
	Or(conds ...gen.Condition) IAppUserDo
	Select(conds ...field.Expr) IAppUserDo
	Where(conds ...gen.Condition) IAppUserDo
	Order(conds ...field.Expr) IAppUserDo
	Distinct(cols ...field.Expr) IAppUserDo
	Omit(cols ...field.Expr) IAppUserDo
	Join(table schema.Tabler, on ...field.Expr) IAppUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppUserDo
	Group(cols ...field.Expr) IAppUserDo
	Having(conds ...gen.Condition) IAppUserDo
	Limit(limit int) IAppUserDo
	Offset(offset int) IAppUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppUserDo
	Unscoped() IAppUserDo
	Create(values ...*database.AppUser) error
	CreateInBatches(values []*database.AppUser, batchSize int) error
	Save(values ...*database.AppUser) error
	First() (*database.AppUser, error)
	Take() (*database.AppUser, error)
	Last() (*database.AppUser, error)
	Find() ([]*database.AppUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.AppUser, err error)
	FindInBatches(result *[]*database.AppUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*database.AppUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppUserDo
	Assign(attrs ...field.AssignExpr) IAppUserDo
	Joins(fields ...field.RelationField) IAppUserDo
	Preload(fields ...field.RelationField) IAppUserDo
	FirstOrInit() (*database.AppUser, error)
	FirstOrCreate() (*database.AppUser, error)
	FindByPage(offset int, limit int) (result []*database.AppUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appUserDo) Debug() IAppUserDo {
	return a.withDO(a.DO.Debug())
}

func (a appUserDo) WithContext(ctx context.Context) IAppUserDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appUserDo) ReadDB() IAppUserDo {
	return a.Clauses(dbresolver.Read)
}

func (a appUserDo) WriteDB() IAppUserDo {
	return a.Clauses(dbresolver.Write)
}

func (a appUserDo) Session(config *gorm.Session) IAppUserDo {
	return a.withDO(a.DO.Session(config))
}

func (a appUserDo) Clauses(conds ...clause.Expression) IAppUserDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appUserDo) Returning(value interface{}, columns ...string) IAppUserDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appUserDo) Not(conds ...gen.Condition) IAppUserDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appUserDo) Or(conds ...gen.Condition) IAppUserDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appUserDo) Select(conds ...field.Expr) IAppUserDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appUserDo) Where(conds ...gen.Condition) IAppUserDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appUserDo) Order(conds ...field.Expr) IAppUserDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appUserDo) Distinct(cols ...field.Expr) IAppUserDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appUserDo) Omit(cols ...field.Expr) IAppUserDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appUserDo) Join(table schema.Tabler, on ...field.Expr) IAppUserDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppUserDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppUserDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appUserDo) Group(cols ...field.Expr) IAppUserDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appUserDo) Having(conds ...gen.Condition) IAppUserDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appUserDo) Limit(limit int) IAppUserDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appUserDo) Offset(offset int) IAppUserDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppUserDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appUserDo) Unscoped() IAppUserDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appUserDo) Create(values ...*database.AppUser) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appUserDo) CreateInBatches(values []*database.AppUser, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appUserDo) Save(values ...*database.AppUser) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appUserDo) First() (*database.AppUser, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppUser), nil
	}
}

func (a appUserDo) Take() (*database.AppUser, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppUser), nil
	}
}

func (a appUserDo) Last() (*database.AppUser, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppUser), nil
	}
}

func (a appUserDo) Find() ([]*database.AppUser, error) {
	result, err := a.DO.Find()
	return result.([]*database.AppUser), err
}

func (a appUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.AppUser, err error) {
	buf := make([]*database.AppUser, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appUserDo) FindInBatches(result *[]*database.AppUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appUserDo) Attrs(attrs ...field.AssignExpr) IAppUserDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appUserDo) Assign(attrs ...field.AssignExpr) IAppUserDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appUserDo) Joins(fields ...field.RelationField) IAppUserDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appUserDo) Preload(fields ...field.RelationField) IAppUserDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appUserDo) FirstOrInit() (*database.AppUser, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppUser), nil
	}
}

func (a appUserDo) FirstOrCreate() (*database.AppUser, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppUser), nil
	}
}

func (a appUserDo) FindByPage(offset int, limit int) (result []*database.AppUser, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appUserDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appUserDo) Delete(models ...*database.AppUser) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appUserDo) withDO(do gen.Dao) *appUserDo {
	a.DO = *do.(*gen.DO)
	return a
}
