// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/fdddf/xcstrings-translator/internal/database"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAppProviderConfig(db *gorm.DB, opts ...gen.DOOption) appProviderConfig {
	_appProviderConfig := appProviderConfig{}

	_appProviderConfig.appProviderConfigDo.UseDB(db, opts...)
	_appProviderConfig.appProviderConfigDo.UseModel(&database.AppProviderConfig{})

	tableName := _appProviderConfig.appProviderConfigDo.TableName()
	_appProviderConfig.ALL = field.NewAsterisk(tableName)
	_appProviderConfig.ID = field.NewUint(tableName, "id")
	_appProviderConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_appProviderConfig.UpdatedAt = field.NewTime(tableName, "updated_at")
	_appProviderConfig.DeletedAt = field.NewField(tableName, "deleted_at")
	_appProviderConfig.AppID = field.NewUint(tableName, "app_id")
	_appProviderConfig.ProviderConfigID = field.NewUint(tableName, "provider_config_id")
	_appProviderConfig.ProviderType = field.NewString(tableName, "provider_type")
	_appProviderConfig.IsDefault = field.NewBool(tableName, "is_default")
	_appProviderConfig.App = appProviderConfigBelongsToApp{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("App", "database.App"),
		User: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("App.User", "database.User"),
		},
	}

	_appProviderConfig.ProviderConfig = appProviderConfigBelongsToProviderConfig{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ProviderConfig", "database.ProviderConfig"),
		User: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ProviderConfig.User", "database.User"),
		},
	}

	_appProviderConfig.fillFieldMap()

	return _appProviderConfig
}

type appProviderConfig struct {
	appProviderConfigDo

	ALL              field.Asterisk
	ID               field.Uint
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	AppID            field.Uint
	ProviderConfigID field.Uint
	ProviderType     field.String
	IsDefault        field.Bool
	App              appProviderConfigBelongsToApp

	ProviderConfig appProviderConfigBelongsToProviderConfig

	fieldMap map[string]field.Expr
}

func (a appProviderConfig) Table(newTableName string) *appProviderConfig {
	a.appProviderConfigDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a appProviderConfig) As(alias string) *appProviderConfig {
	a.appProviderConfigDo.DO = *(a.appProviderConfigDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *appProviderConfig) updateTableName(table string) *appProviderConfig {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.AppID = field.NewUint(table, "app_id")
	a.ProviderConfigID = field.NewUint(table, "provider_config_id")
	a.ProviderType = field.NewString(table, "provider_type")
	a.IsDefault = field.NewBool(table, "is_default")

	a.fillFieldMap()

	return a
}

func (a *appProviderConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *appProviderConfig) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["app_id"] = a.AppID
	a.fieldMap["provider_config_id"] = a.ProviderConfigID
	a.fieldMap["provider_type"] = a.ProviderType
	a.fieldMap["is_default"] = a.IsDefault

}

func (a appProviderConfig) clone(db *gorm.DB) appProviderConfig {
	a.appProviderConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	a.App.db = db.Session(&gorm.Session{Initialized: true})
	a.App.db.Statement.ConnPool = db.Statement.ConnPool
	a.ProviderConfig.db = db.Session(&gorm.Session{Initialized: true})
	a.ProviderConfig.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a appProviderConfig) replaceDB(db *gorm.DB) appProviderConfig {
	a.appProviderConfigDo.ReplaceDB(db)
	a.App.db = db.Session(&gorm.Session{})
	a.ProviderConfig.db = db.Session(&gorm.Session{})
	return a
}

type appProviderConfigBelongsToApp struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
	}
}

func (a appProviderConfigBelongsToApp) Where(conds ...field.Expr) *appProviderConfigBelongsToApp {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a appProviderConfigBelongsToApp) WithContext(ctx context.Context) *appProviderConfigBelongsToApp {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a appProviderConfigBelongsToApp) Session(session *gorm.Session) *appProviderConfigBelongsToApp {
	a.db = a.db.Session(session)
	return &a
}

func (a appProviderConfigBelongsToApp) Model(m *database.AppProviderConfig) *appProviderConfigBelongsToAppTx {
	return &appProviderConfigBelongsToAppTx{a.db.Model(m).Association(a.Name())}
}

func (a appProviderConfigBelongsToApp) Unscoped() *appProviderConfigBelongsToApp {
	a.db = a.db.Unscoped()
	return &a
}

type appProviderConfigBelongsToAppTx struct{ tx *gorm.Association }

func (a appProviderConfigBelongsToAppTx) Find() (result *database.App, err error) {
	return result, a.tx.Find(&result)
}

func (a appProviderConfigBelongsToAppTx) Append(values ...*database.App) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a appProviderConfigBelongsToAppTx) Replace(values ...*database.App) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a appProviderConfigBelongsToAppTx) Delete(values ...*database.App) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a appProviderConfigBelongsToAppTx) Clear() error {
	return a.tx.Clear()
}

func (a appProviderConfigBelongsToAppTx) Count() int64 {
	return a.tx.Count()
}

func (a appProviderConfigBelongsToAppTx) Unscoped() *appProviderConfigBelongsToAppTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type appProviderConfigBelongsToProviderConfig struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
	}
}

func (a appProviderConfigBelongsToProviderConfig) Where(conds ...field.Expr) *appProviderConfigBelongsToProviderConfig {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a appProviderConfigBelongsToProviderConfig) WithContext(ctx context.Context) *appProviderConfigBelongsToProviderConfig {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a appProviderConfigBelongsToProviderConfig) Session(session *gorm.Session) *appProviderConfigBelongsToProviderConfig {
	a.db = a.db.Session(session)
	return &a
}

func (a appProviderConfigBelongsToProviderConfig) Model(m *database.AppProviderConfig) *appProviderConfigBelongsToProviderConfigTx {
	return &appProviderConfigBelongsToProviderConfigTx{a.db.Model(m).Association(a.Name())}
}

func (a appProviderConfigBelongsToProviderConfig) Unscoped() *appProviderConfigBelongsToProviderConfig {
	a.db = a.db.Unscoped()
	return &a
}

type appProviderConfigBelongsToProviderConfigTx struct{ tx *gorm.Association }

func (a appProviderConfigBelongsToProviderConfigTx) Find() (result *database.ProviderConfig, err error) {
	return result, a.tx.Find(&result)
}

func (a appProviderConfigBelongsToProviderConfigTx) Append(values ...*database.ProviderConfig) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a appProviderConfigBelongsToProviderConfigTx) Replace(values ...*database.ProviderConfig) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a appProviderConfigBelongsToProviderConfigTx) Delete(values ...*database.ProviderConfig) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a appProviderConfigBelongsToProviderConfigTx) Clear() error {
	return a.tx.Clear()
}

func (a appProviderConfigBelongsToProviderConfigTx) Count() int64 {
	return a.tx.Count()
}

func (a appProviderConfigBelongsToProviderConfigTx) Unscoped() *appProviderConfigBelongsToProviderConfigTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type appProviderConfigDo struct{ gen.DO }

type IAppProviderConfigDo interface {
	gen.SubQuery
	Debug() IAppProviderConfigDo
	WithContext(ctx context.Context) IAppProviderConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAppProviderConfigDo
	WriteDB() IAppProviderConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAppProviderConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAppProviderConfigDo
	Not(conds ...gen.Condition) IAppProviderConfigDo
	Or(conds ...gen.Condition) IAppProviderConfigDo
	Select(conds ...field.Expr) IAppProviderConfigDo
	Where(conds ...gen.Condition) IAppProviderConfigDo
	Order(conds ...field.Expr) IAppProviderConfigDo
	Distinct(cols ...field.Expr) IAppProviderConfigDo
	Omit(cols ...field.Expr) IAppProviderConfigDo
	Join(table schema.Tabler, on ...field.Expr) IAppProviderConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAppProviderConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAppProviderConfigDo
	Group(cols ...field.Expr) IAppProviderConfigDo
	Having(conds ...gen.Condition) IAppProviderConfigDo
	Limit(limit int) IAppProviderConfigDo
	Offset(offset int) IAppProviderConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAppProviderConfigDo
	Unscoped() IAppProviderConfigDo
	Create(values ...*database.AppProviderConfig) error
	CreateInBatches(values []*database.AppProviderConfig, batchSize int) error
	Save(values ...*database.AppProviderConfig) error
	First() (*database.AppProviderConfig, error)
	Take() (*database.AppProviderConfig, error)
	Last() (*database.AppProviderConfig, error)
	Find() ([]*database.AppProviderConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.AppProviderConfig, err error)
	FindInBatches(result *[]*database.AppProviderConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*database.AppProviderConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAppProviderConfigDo
	Assign(attrs ...field.AssignExpr) IAppProviderConfigDo
	Joins(fields ...field.RelationField) IAppProviderConfigDo
	Preload(fields ...field.RelationField) IAppProviderConfigDo
	FirstOrInit() (*database.AppProviderConfig, error)
	FirstOrCreate() (*database.AppProviderConfig, error)
	FindByPage(offset int, limit int) (result []*database.AppProviderConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAppProviderConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a appProviderConfigDo) Debug() IAppProviderConfigDo {
	return a.withDO(a.DO.Debug())
}

func (a appProviderConfigDo) WithContext(ctx context.Context) IAppProviderConfigDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a appProviderConfigDo) ReadDB() IAppProviderConfigDo {
	return a.Clauses(dbresolver.Read)
}

func (a appProviderConfigDo) WriteDB() IAppProviderConfigDo {
	return a.Clauses(dbresolver.Write)
}

func (a appProviderConfigDo) Session(config *gorm.Session) IAppProviderConfigDo {
	return a.withDO(a.DO.Session(config))
}

func (a appProviderConfigDo) Clauses(conds ...clause.Expression) IAppProviderConfigDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a appProviderConfigDo) Returning(value interface{}, columns ...string) IAppProviderConfigDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a appProviderConfigDo) Not(conds ...gen.Condition) IAppProviderConfigDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a appProviderConfigDo) Or(conds ...gen.Condition) IAppProviderConfigDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a appProviderConfigDo) Select(conds ...field.Expr) IAppProviderConfigDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a appProviderConfigDo) Where(conds ...gen.Condition) IAppProviderConfigDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a appProviderConfigDo) Order(conds ...field.Expr) IAppProviderConfigDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a appProviderConfigDo) Distinct(cols ...field.Expr) IAppProviderConfigDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a appProviderConfigDo) Omit(cols ...field.Expr) IAppProviderConfigDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a appProviderConfigDo) Join(table schema.Tabler, on ...field.Expr) IAppProviderConfigDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a appProviderConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAppProviderConfigDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a appProviderConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IAppProviderConfigDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a appProviderConfigDo) Group(cols ...field.Expr) IAppProviderConfigDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a appProviderConfigDo) Having(conds ...gen.Condition) IAppProviderConfigDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a appProviderConfigDo) Limit(limit int) IAppProviderConfigDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a appProviderConfigDo) Offset(offset int) IAppProviderConfigDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a appProviderConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAppProviderConfigDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a appProviderConfigDo) Unscoped() IAppProviderConfigDo {
	return a.withDO(a.DO.Unscoped())
}

func (a appProviderConfigDo) Create(values ...*database.AppProviderConfig) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a appProviderConfigDo) CreateInBatches(values []*database.AppProviderConfig, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a appProviderConfigDo) Save(values ...*database.AppProviderConfig) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a appProviderConfigDo) First() (*database.AppProviderConfig, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppProviderConfig), nil
	}
}

func (a appProviderConfigDo) Take() (*database.AppProviderConfig, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppProviderConfig), nil
	}
}

func (a appProviderConfigDo) Last() (*database.AppProviderConfig, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppProviderConfig), nil
	}
}

func (a appProviderConfigDo) Find() ([]*database.AppProviderConfig, error) {
	result, err := a.DO.Find()
	return result.([]*database.AppProviderConfig), err
}

func (a appProviderConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.AppProviderConfig, err error) {
	buf := make([]*database.AppProviderConfig, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a appProviderConfigDo) FindInBatches(result *[]*database.AppProviderConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a appProviderConfigDo) Attrs(attrs ...field.AssignExpr) IAppProviderConfigDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a appProviderConfigDo) Assign(attrs ...field.AssignExpr) IAppProviderConfigDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a appProviderConfigDo) Joins(fields ...field.RelationField) IAppProviderConfigDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a appProviderConfigDo) Preload(fields ...field.RelationField) IAppProviderConfigDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a appProviderConfigDo) FirstOrInit() (*database.AppProviderConfig, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppProviderConfig), nil
	}
}

func (a appProviderConfigDo) FirstOrCreate() (*database.AppProviderConfig, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*database.AppProviderConfig), nil
	}
}

func (a appProviderConfigDo) FindByPage(offset int, limit int) (result []*database.AppProviderConfig, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a appProviderConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a appProviderConfigDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a appProviderConfigDo) Delete(models ...*database.AppProviderConfig) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *appProviderConfigDo) withDO(do gen.Dao) *appProviderConfigDo {
	a.DO = *do.(*gen.DO)
	return a
}
