// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/fdddf/opentrans/internal/database"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newTranslation(db *gorm.DB, opts ...gen.DOOption) translation {
	_translation := translation{}

	_translation.translationDo.UseDB(db, opts...)
	_translation.translationDo.UseModel(&database.Translation{})

	tableName := _translation.translationDo.TableName()
	_translation.ALL = field.NewAsterisk(tableName)
	_translation.ID = field.NewUint(tableName, "id")
	_translation.CreatedAt = field.NewTime(tableName, "created_at")
	_translation.UpdatedAt = field.NewTime(tableName, "updated_at")
	_translation.DeletedAt = field.NewField(tableName, "deleted_at")
	_translation.ProjectID = field.NewUint(tableName, "project_id")
	_translation.Key = field.NewString(tableName, "key")
	_translation.SourceText = field.NewString(tableName, "source_text")
	_translation.TargetText = field.NewString(tableName, "target_text")
	_translation.TargetLanguage = field.NewString(tableName, "target_language")
	_translation.State = field.NewString(tableName, "state")
	_translation.TranslationProvider = field.NewString(tableName, "translation_provider")
	_translation.Project = translationBelongsToProject{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Project", "database.Project"),
		User: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Project.User", "database.User"),
		},
	}

	_translation.fillFieldMap()

	return _translation
}

type translation struct {
	translationDo

	ALL                 field.Asterisk
	ID                  field.Uint
	CreatedAt           field.Time
	UpdatedAt           field.Time
	DeletedAt           field.Field
	ProjectID           field.Uint
	Key                 field.String
	SourceText          field.String
	TargetText          field.String
	TargetLanguage      field.String
	State               field.String
	TranslationProvider field.String
	Project             translationBelongsToProject

	fieldMap map[string]field.Expr
}

func (t translation) Table(newTableName string) *translation {
	t.translationDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t translation) As(alias string) *translation {
	t.translationDo.DO = *(t.translationDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *translation) updateTableName(table string) *translation {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")
	t.ProjectID = field.NewUint(table, "project_id")
	t.Key = field.NewString(table, "key")
	t.SourceText = field.NewString(table, "source_text")
	t.TargetText = field.NewString(table, "target_text")
	t.TargetLanguage = field.NewString(table, "target_language")
	t.State = field.NewString(table, "state")
	t.TranslationProvider = field.NewString(table, "translation_provider")

	t.fillFieldMap()

	return t
}

func (t *translation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *translation) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["key"] = t.Key
	t.fieldMap["source_text"] = t.SourceText
	t.fieldMap["target_text"] = t.TargetText
	t.fieldMap["target_language"] = t.TargetLanguage
	t.fieldMap["state"] = t.State
	t.fieldMap["translation_provider"] = t.TranslationProvider

}

func (t translation) clone(db *gorm.DB) translation {
	t.translationDo.ReplaceConnPool(db.Statement.ConnPool)
	t.Project.db = db.Session(&gorm.Session{Initialized: true})
	t.Project.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t translation) replaceDB(db *gorm.DB) translation {
	t.translationDo.ReplaceDB(db)
	t.Project.db = db.Session(&gorm.Session{})
	return t
}

type translationBelongsToProject struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
	}
}

func (a translationBelongsToProject) Where(conds ...field.Expr) *translationBelongsToProject {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a translationBelongsToProject) WithContext(ctx context.Context) *translationBelongsToProject {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a translationBelongsToProject) Session(session *gorm.Session) *translationBelongsToProject {
	a.db = a.db.Session(session)
	return &a
}

func (a translationBelongsToProject) Model(m *database.Translation) *translationBelongsToProjectTx {
	return &translationBelongsToProjectTx{a.db.Model(m).Association(a.Name())}
}

func (a translationBelongsToProject) Unscoped() *translationBelongsToProject {
	a.db = a.db.Unscoped()
	return &a
}

type translationBelongsToProjectTx struct{ tx *gorm.Association }

func (a translationBelongsToProjectTx) Find() (result *database.Project, err error) {
	return result, a.tx.Find(&result)
}

func (a translationBelongsToProjectTx) Append(values ...*database.Project) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a translationBelongsToProjectTx) Replace(values ...*database.Project) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a translationBelongsToProjectTx) Delete(values ...*database.Project) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a translationBelongsToProjectTx) Clear() error {
	return a.tx.Clear()
}

func (a translationBelongsToProjectTx) Count() int64 {
	return a.tx.Count()
}

func (a translationBelongsToProjectTx) Unscoped() *translationBelongsToProjectTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type translationDo struct{ gen.DO }

type ITranslationDo interface {
	gen.SubQuery
	Debug() ITranslationDo
	WithContext(ctx context.Context) ITranslationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITranslationDo
	WriteDB() ITranslationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITranslationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITranslationDo
	Not(conds ...gen.Condition) ITranslationDo
	Or(conds ...gen.Condition) ITranslationDo
	Select(conds ...field.Expr) ITranslationDo
	Where(conds ...gen.Condition) ITranslationDo
	Order(conds ...field.Expr) ITranslationDo
	Distinct(cols ...field.Expr) ITranslationDo
	Omit(cols ...field.Expr) ITranslationDo
	Join(table schema.Tabler, on ...field.Expr) ITranslationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITranslationDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITranslationDo
	Group(cols ...field.Expr) ITranslationDo
	Having(conds ...gen.Condition) ITranslationDo
	Limit(limit int) ITranslationDo
	Offset(offset int) ITranslationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITranslationDo
	Unscoped() ITranslationDo
	Create(values ...*database.Translation) error
	CreateInBatches(values []*database.Translation, batchSize int) error
	Save(values ...*database.Translation) error
	First() (*database.Translation, error)
	Take() (*database.Translation, error)
	Last() (*database.Translation, error)
	Find() ([]*database.Translation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.Translation, err error)
	FindInBatches(result *[]*database.Translation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*database.Translation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITranslationDo
	Assign(attrs ...field.AssignExpr) ITranslationDo
	Joins(fields ...field.RelationField) ITranslationDo
	Preload(fields ...field.RelationField) ITranslationDo
	FirstOrInit() (*database.Translation, error)
	FirstOrCreate() (*database.Translation, error)
	FindByPage(offset int, limit int) (result []*database.Translation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITranslationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t translationDo) Debug() ITranslationDo {
	return t.withDO(t.DO.Debug())
}

func (t translationDo) WithContext(ctx context.Context) ITranslationDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t translationDo) ReadDB() ITranslationDo {
	return t.Clauses(dbresolver.Read)
}

func (t translationDo) WriteDB() ITranslationDo {
	return t.Clauses(dbresolver.Write)
}

func (t translationDo) Session(config *gorm.Session) ITranslationDo {
	return t.withDO(t.DO.Session(config))
}

func (t translationDo) Clauses(conds ...clause.Expression) ITranslationDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t translationDo) Returning(value interface{}, columns ...string) ITranslationDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t translationDo) Not(conds ...gen.Condition) ITranslationDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t translationDo) Or(conds ...gen.Condition) ITranslationDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t translationDo) Select(conds ...field.Expr) ITranslationDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t translationDo) Where(conds ...gen.Condition) ITranslationDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t translationDo) Order(conds ...field.Expr) ITranslationDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t translationDo) Distinct(cols ...field.Expr) ITranslationDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t translationDo) Omit(cols ...field.Expr) ITranslationDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t translationDo) Join(table schema.Tabler, on ...field.Expr) ITranslationDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t translationDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITranslationDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t translationDo) RightJoin(table schema.Tabler, on ...field.Expr) ITranslationDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t translationDo) Group(cols ...field.Expr) ITranslationDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t translationDo) Having(conds ...gen.Condition) ITranslationDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t translationDo) Limit(limit int) ITranslationDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t translationDo) Offset(offset int) ITranslationDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t translationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITranslationDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t translationDo) Unscoped() ITranslationDo {
	return t.withDO(t.DO.Unscoped())
}

func (t translationDo) Create(values ...*database.Translation) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t translationDo) CreateInBatches(values []*database.Translation, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t translationDo) Save(values ...*database.Translation) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t translationDo) First() (*database.Translation, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*database.Translation), nil
	}
}

func (t translationDo) Take() (*database.Translation, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*database.Translation), nil
	}
}

func (t translationDo) Last() (*database.Translation, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*database.Translation), nil
	}
}

func (t translationDo) Find() ([]*database.Translation, error) {
	result, err := t.DO.Find()
	return result.([]*database.Translation), err
}

func (t translationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.Translation, err error) {
	buf := make([]*database.Translation, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t translationDo) FindInBatches(result *[]*database.Translation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t translationDo) Attrs(attrs ...field.AssignExpr) ITranslationDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t translationDo) Assign(attrs ...field.AssignExpr) ITranslationDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t translationDo) Joins(fields ...field.RelationField) ITranslationDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t translationDo) Preload(fields ...field.RelationField) ITranslationDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t translationDo) FirstOrInit() (*database.Translation, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*database.Translation), nil
	}
}

func (t translationDo) FirstOrCreate() (*database.Translation, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*database.Translation), nil
	}
}

func (t translationDo) FindByPage(offset int, limit int) (result []*database.Translation, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t translationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t translationDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t translationDo) Delete(models ...*database.Translation) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *translationDo) withDO(do gen.Dao) *translationDo {
	t.DO = *do.(*gen.DO)
	return t
}
