// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/fdddf/opentrans/internal/database"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newTranslationQueue(db *gorm.DB, opts ...gen.DOOption) translationQueue {
	_translationQueue := translationQueue{}

	_translationQueue.translationQueueDo.UseDB(db, opts...)
	_translationQueue.translationQueueDo.UseModel(&database.TranslationQueue{})

	tableName := _translationQueue.translationQueueDo.TableName()
	_translationQueue.ALL = field.NewAsterisk(tableName)
	_translationQueue.ID = field.NewUint(tableName, "id")
	_translationQueue.CreatedAt = field.NewTime(tableName, "created_at")
	_translationQueue.UpdatedAt = field.NewTime(tableName, "updated_at")
	_translationQueue.DeletedAt = field.NewField(tableName, "deleted_at")
	_translationQueue.UserID = field.NewUint(tableName, "user_id")
	_translationQueue.ProjectID = field.NewUint(tableName, "project_id")
	_translationQueue.AppID = field.NewUint(tableName, "app_id")
	_translationQueue.Type = field.NewString(tableName, "type")
	_translationQueue.Status = field.NewString(tableName, "status")
	_translationQueue.Priority = field.NewInt(tableName, "priority")
	_translationQueue.Progress = field.NewInt(tableName, "progress")
	_translationQueue.Total = field.NewInt(tableName, "total")
	_translationQueue.Done = field.NewInt(tableName, "done")
	_translationQueue.Error = field.NewString(tableName, "error")
	_translationQueue.ProviderType = field.NewString(tableName, "provider_type")
	_translationQueue.SourceLanguage = field.NewString(tableName, "source_language")
	_translationQueue.TargetLanguages = field.NewField(tableName, "target_languages")
	_translationQueue.ConfigData = field.NewField(tableName, "config_data")
	_translationQueue.ResultData = field.NewField(tableName, "result_data")

	_translationQueue.fillFieldMap()

	return _translationQueue
}

type translationQueue struct {
	translationQueueDo

	ALL             field.Asterisk
	ID              field.Uint
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field
	UserID          field.Uint
	ProjectID       field.Uint
	AppID           field.Uint
	Type            field.String
	Status          field.String
	Priority        field.Int
	Progress        field.Int
	Total           field.Int
	Done            field.Int
	Error           field.String
	ProviderType    field.String
	SourceLanguage  field.String
	TargetLanguages field.Field
	ConfigData      field.Field
	ResultData      field.Field

	fieldMap map[string]field.Expr
}

func (t translationQueue) Table(newTableName string) *translationQueue {
	t.translationQueueDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t translationQueue) As(alias string) *translationQueue {
	t.translationQueueDo.DO = *(t.translationQueueDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *translationQueue) updateTableName(table string) *translationQueue {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")
	t.UserID = field.NewUint(table, "user_id")
	t.ProjectID = field.NewUint(table, "project_id")
	t.AppID = field.NewUint(table, "app_id")
	t.Type = field.NewString(table, "type")
	t.Status = field.NewString(table, "status")
	t.Priority = field.NewInt(table, "priority")
	t.Progress = field.NewInt(table, "progress")
	t.Total = field.NewInt(table, "total")
	t.Done = field.NewInt(table, "done")
	t.Error = field.NewString(table, "error")
	t.ProviderType = field.NewString(table, "provider_type")
	t.SourceLanguage = field.NewString(table, "source_language")
	t.TargetLanguages = field.NewField(table, "target_languages")
	t.ConfigData = field.NewField(table, "config_data")
	t.ResultData = field.NewField(table, "result_data")

	t.fillFieldMap()

	return t
}

func (t *translationQueue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *translationQueue) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 19)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["project_id"] = t.ProjectID
	t.fieldMap["app_id"] = t.AppID
	t.fieldMap["type"] = t.Type
	t.fieldMap["status"] = t.Status
	t.fieldMap["priority"] = t.Priority
	t.fieldMap["progress"] = t.Progress
	t.fieldMap["total"] = t.Total
	t.fieldMap["done"] = t.Done
	t.fieldMap["error"] = t.Error
	t.fieldMap["provider_type"] = t.ProviderType
	t.fieldMap["source_language"] = t.SourceLanguage
	t.fieldMap["target_languages"] = t.TargetLanguages
	t.fieldMap["config_data"] = t.ConfigData
	t.fieldMap["result_data"] = t.ResultData
}

func (t translationQueue) clone(db *gorm.DB) translationQueue {
	t.translationQueueDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t translationQueue) replaceDB(db *gorm.DB) translationQueue {
	t.translationQueueDo.ReplaceDB(db)
	return t
}

type translationQueueDo struct{ gen.DO }

type ITranslationQueueDo interface {
	gen.SubQuery
	Debug() ITranslationQueueDo
	WithContext(ctx context.Context) ITranslationQueueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITranslationQueueDo
	WriteDB() ITranslationQueueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITranslationQueueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITranslationQueueDo
	Not(conds ...gen.Condition) ITranslationQueueDo
	Or(conds ...gen.Condition) ITranslationQueueDo
	Select(conds ...field.Expr) ITranslationQueueDo
	Where(conds ...gen.Condition) ITranslationQueueDo
	Order(conds ...field.Expr) ITranslationQueueDo
	Distinct(cols ...field.Expr) ITranslationQueueDo
	Omit(cols ...field.Expr) ITranslationQueueDo
	Join(table schema.Tabler, on ...field.Expr) ITranslationQueueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITranslationQueueDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITranslationQueueDo
	Group(cols ...field.Expr) ITranslationQueueDo
	Having(conds ...gen.Condition) ITranslationQueueDo
	Limit(limit int) ITranslationQueueDo
	Offset(offset int) ITranslationQueueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITranslationQueueDo
	Unscoped() ITranslationQueueDo
	Create(values ...*database.TranslationQueue) error
	CreateInBatches(values []*database.TranslationQueue, batchSize int) error
	Save(values ...*database.TranslationQueue) error
	First() (*database.TranslationQueue, error)
	Take() (*database.TranslationQueue, error)
	Last() (*database.TranslationQueue, error)
	Find() ([]*database.TranslationQueue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.TranslationQueue, err error)
	FindInBatches(result *[]*database.TranslationQueue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*database.TranslationQueue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITranslationQueueDo
	Assign(attrs ...field.AssignExpr) ITranslationQueueDo
	Joins(fields ...field.RelationField) ITranslationQueueDo
	Preload(fields ...field.RelationField) ITranslationQueueDo
	FirstOrInit() (*database.TranslationQueue, error)
	FirstOrCreate() (*database.TranslationQueue, error)
	FindByPage(offset int, limit int) (result []*database.TranslationQueue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITranslationQueueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t translationQueueDo) Debug() ITranslationQueueDo {
	return t.withDO(t.DO.Debug())
}

func (t translationQueueDo) WithContext(ctx context.Context) ITranslationQueueDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t translationQueueDo) ReadDB() ITranslationQueueDo {
	return t.Clauses(dbresolver.Read)
}

func (t translationQueueDo) WriteDB() ITranslationQueueDo {
	return t.Clauses(dbresolver.Write)
}

func (t translationQueueDo) Session(config *gorm.Session) ITranslationQueueDo {
	return t.withDO(t.DO.Session(config))
}

func (t translationQueueDo) Clauses(conds ...clause.Expression) ITranslationQueueDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t translationQueueDo) Returning(value interface{}, columns ...string) ITranslationQueueDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t translationQueueDo) Not(conds ...gen.Condition) ITranslationQueueDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t translationQueueDo) Or(conds ...gen.Condition) ITranslationQueueDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t translationQueueDo) Select(conds ...field.Expr) ITranslationQueueDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t translationQueueDo) Where(conds ...gen.Condition) ITranslationQueueDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t translationQueueDo) Order(conds ...field.Expr) ITranslationQueueDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t translationQueueDo) Distinct(cols ...field.Expr) ITranslationQueueDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t translationQueueDo) Omit(cols ...field.Expr) ITranslationQueueDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t translationQueueDo) Join(table schema.Tabler, on ...field.Expr) ITranslationQueueDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t translationQueueDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITranslationQueueDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t translationQueueDo) RightJoin(table schema.Tabler, on ...field.Expr) ITranslationQueueDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t translationQueueDo) Group(cols ...field.Expr) ITranslationQueueDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t translationQueueDo) Having(conds ...gen.Condition) ITranslationQueueDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t translationQueueDo) Limit(limit int) ITranslationQueueDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t translationQueueDo) Offset(offset int) ITranslationQueueDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t translationQueueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITranslationQueueDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t translationQueueDo) Unscoped() ITranslationQueueDo {
	return t.withDO(t.DO.Unscoped())
}

func (t translationQueueDo) Create(values ...*database.TranslationQueue) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t translationQueueDo) CreateInBatches(values []*database.TranslationQueue, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t translationQueueDo) Save(values ...*database.TranslationQueue) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t translationQueueDo) First() (*database.TranslationQueue, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*database.TranslationQueue), nil
	}
}

func (t translationQueueDo) Take() (*database.TranslationQueue, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*database.TranslationQueue), nil
	}
}

func (t translationQueueDo) Last() (*database.TranslationQueue, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*database.TranslationQueue), nil
	}
}

func (t translationQueueDo) Find() ([]*database.TranslationQueue, error) {
	result, err := t.DO.Find()
	return result.([]*database.TranslationQueue), err
}

func (t translationQueueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.TranslationQueue, err error) {
	buf := make([]*database.TranslationQueue, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t translationQueueDo) FindInBatches(result *[]*database.TranslationQueue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t translationQueueDo) Attrs(attrs ...field.AssignExpr) ITranslationQueueDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t translationQueueDo) Assign(attrs ...field.AssignExpr) ITranslationQueueDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t translationQueueDo) Joins(fields ...field.RelationField) ITranslationQueueDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t translationQueueDo) Preload(fields ...field.RelationField) ITranslationQueueDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t translationQueueDo) FirstOrInit() (*database.TranslationQueue, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*database.TranslationQueue), nil
	}
}

func (t translationQueueDo) FirstOrCreate() (*database.TranslationQueue, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*database.TranslationQueue), nil
	}
}

func (t translationQueueDo) FindByPage(offset int, limit int) (result []*database.TranslationQueue, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t translationQueueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t translationQueueDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t translationQueueDo) Delete(models ...*database.TranslationQueue) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *translationQueueDo) withDO(do gen.Dao) *translationQueueDo {
	t.DO = *do.(*gen.DO)
	return t
}
